- id: forbid-secrets
  name: Check for unencrypted Kubernetes secrets in manifests and SOPS encrypt them
  description: "Find files containing unencrypted Kubernetes secrets and SOPS encrypt them"
  entry: forbid_secrets
  language: python
  files: ((^|/)*.(ya?ml)$)
