- id: aws-access-key-id
  name: Check for AWS Access Key IDs
  entry: forbid_secrets --hook-id aws-access-key-id
  language: python
  files: ((^|/)*.(ya?ml)$)
  additional_dependencies: ['argparse','datetime', 'PyYAML']
- id: aws-secret-access-key
  name: Check for AWS Secret Access Keys
  entry: forbid_secrets --hook-id aws-secret-access-key
  language: python
  files: ((^|/)*.(ya?ml)$)
  additional_dependencies: ['argparse','datetime', 'PyYAML']
- id: gcp-api-key
  name: Check for GCP API Keys
  entry: forbid_secrets --hook-id gcp-api-key
  language: python
  files: ((^|/)*.(ya?ml)$)
  additional_dependencies: ['argparse','datetime', 'PyYAML']
- id: generic-api-key
  name: Check for Generic API Keys
  entry: forbid_secrets --hook-id generic-api-key
  language: python
  files: ((^|/)*.(ya?ml)$)
  additional_dependencies: ['argparse','datetime', 'PyYAML']
- id: github-access-token
  name: Check for GitHub Access Tokens
  entry: forbid_secrets --hook-id github-access-token
  language: python
  files: ((^|/)*.(ya?ml)$)
  additional_dependencies: ['argparse','datetime', 'PyYAML']
- id: google-oauth-client-secret
  name: Check for Google OAuth Client Secrets
  entry: forbid_secrets --hook-id google-oauth-client-secret
  language: python
  files: ((^|/)*.(ya?ml)$)
  additional_dependencies: ['argparse','datetime', 'PyYAML']
- id: jwt
  name: Check for JSON Web Tokens (JWT)
  entry: forbid_secrets --hook-id jwt
  language: python
  files: ((^|/)*.(ya?ml)$)
  additional_dependencies: ['argparse','datetime', 'PyYAML']
- id: kubernetes-secret
  name: Check for unencrypted Kubernetes secrets
  entry: forbid_secrets --hook-id kubernetes-secret
  language: python
  files: ((^|/)*.(ya?ml)$)
  additional_dependencies: ['argparse','datetime', 'PyYAML']
- id: rsa-private-key
  name: Check for RSA Private Keys
  entry: forbid_secrets --hook-id rsa-private-key
  language: python
  files: ((^|/)*.(ya?ml)$)
  additional_dependencies: ['argparse','datetime', 'PyYAML']
- id: slack-webhook-url
  name: Check for Slack Webhook URLs
  entry: forbid_secrets --hook-id slack-webhook-url
  language: python
  files: ((^|/)*.(ya?ml)$)
  additional_dependencies: ['argparse','datetime', 'PyYAML']
- id: ssh-private-key
  name: Check for SSH Private Keys
  entry: forbid_secrets --hook-id ssh-private-key
  language: python
  files: ((^|/)*.(ya?ml)$)
  additional_dependencies: ['argparse','datetime', 'PyYAML']