# vim: ff=unix ts=2 sw=2 ai expandtab
---
# .pre-commit-config.yaml for development environment
fail_fast: true
# Define the pre-commit hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-ast
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: check-json
      - id: check-case-conflict
      # This hook is disabled because we deal with this in our
      # sops-pre-commit hook and also in black
      # - id: detect-private-key

  - repo: https://github.com/psf/black
    rev: 24.4.2
    hooks:
      - id: black
        language_version: python3  # Specify the Python version

  # mypy is a static type checker for Python
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.10.1
    hooks:
      - id: mypy

  - repo: https://github.com/PyCQA/flake8
    rev: 7.1.0
    hooks:
      - id: flake8
        additional_dependencies: [
          # Tool for encouraging best coding practices and helping ensure
          # Python code is secure.
          dlint,
          # Check the order of import statements and the __all__ list.
          # flake8-alphabetize,
          # Wrapper around bandit - https://github.com/PyCQA/bandit
          # flake8-bandit,
          # Finding likely bugs and design problems in your program.
          flake8-bugbear,
          # Checks if everything has a docstring.
          flake8-docstring-checker,
          # flake8-docstrings-complete, # Linter that checks docstrings of
          # functions, methods and classes.
          # flake8-fastapi,             # Checks FastAPI code against
          # opinionated style rules.
          # flake8-github,              # Generates GitHub annotation for PR's.
          # flake8-requirements,        # Package requirements checker.
          # flake8-spellcheck,          # Spellcheck variables, classnames,
          # comments, docstrings etc.
          # flake8-sphinx-links,        # Check docstrings for double backticked
          # strings which should be links to the Python documentation.
          # flake8-unused-arguments,    # Warn against unused arguments in
          # functions.
          # pep8-naming,                # Check the PEP-8 naming conventions.
          # pydoclint,                  # A Python docstring linter that checks
          # arguments, returns, yields, and raises sections.
        ]  # Additional flake8 plugins


  - repo: https://github.com/pylint-dev/pylint
    rev: v3.2.5  # Use the latest stable release
    hooks:
      - id: pylint
      # Example of disabling specific pylint categories
      # args: ["--disable=R,C"]

#  - repo: https://github.com/adrienverge/yamllint
#    rev: v1.35.1
#    hooks:
#      - id: yamllint

  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.3.1
    hooks:
      - id: forbid-crlf
      - id: remove-crlf
      - id: forbid-tabs
      - id: remove-tabs
