name: 01 Feature PR 🤖

on:
  push:
    branches-ignore:
    - main
    - master
    - release
    - pre-release
  workflow_dispatch: {}

jobs:
  pre_release_test_and_pr:
    uses: ./.github/workflows/tasks-python-test-pr.yaml
    with:
      stage: "pre-release"
