name: 02 Pre Release PR 🥳

on:
  push:
    branches:
    - pre-release
  workflow_dispatch: {}

jobs:
  release_test_and_pr:
    uses: ./.github/workflows/tasks-python-test-pr.yaml
    with:
      stage: "release"
    secrets:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

  pre_release_release:
    uses: ./.github/workflows/tasks-node-release-pypi.yaml
    with:
      stage: "release"
    secrets:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      PYPI_USER_AGENT: ${{ secrets.PYPI_USER_AGENT }}
      TEST_PYPI_USER_AGENT: ${{ secrets.TEST_PYPI_USER_AGENT }}
