---
# .github/workflows/tasks-node.yml
name: Node Tasks

on:
  workflow_call:
    inputs:
      stage:
        description: 'Workflow Stage'
        required: true
        type: string

jobs:
  tasks_node:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.1.7
        with:
          fetch-depth: 0

      - name: Starting Stage
        run: "echo Starting Node Stage: ${{ inputs.stage }}"

      - name: Set up environment variables & git config
        run: |
          .github/workflows/tasks-setup-variables.sh
          .github/workflows/tasks-setup-git.sh

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22.4.x"

      - name: Load Node.js cache
        uses: actions/cache@v4.0.2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-cache
          restore-keys: |
            ${{ runner.os }}-node-cache-

      - name: Install Node.js dependencies
        run: |
          npm install

      - name: Run semantic-release
        run: .github/workflows/tasks-semantic-release.sh ${{ inputs.stage }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit changes
        run: |
          git add .
          git commit -m "chore(${{ inputs.stage }}): ${{ env.RELEASE_VERSION }} [skip ci]" || echo "No changes to commit"
          git push origin ${{ inputs.stage }}

      # Check if PR exists, if it doesn't create one with a generated title using
      # pr-title-generate
      - name: Create or Update PR
        id: pr
        run: |
          PR_URL=$(poetry run gh pr list --head $BRANCH_CURRENT --json url --jq '.[0].url' || echo "")
          PR_TITLE=$(poetry run pr-title-generate)
          echo "PR_TITLE: $PR_TITLE"
          if [ -z "$PR_URL" ]; then
            echo "Creating $STAGE_CAP PR"
            PR_URL=$(poetry run gh pr create --title "$STAGE_CAP $BRANCH_CURRENT" --body "This PR was automatically generated by a GitHub Action" --base $BASE_BRANCH --head $BRANCH_CURRENT)
            echo "PR_URL: $PR_URL"
          fi
          PR_BODY=$(poetry run python3 .github/workflows/pr_body_gen.py $BRANCH_CURRENT $BASE_BRANCH)
          poetry run gh pr edit $PR_URL --title "$PR_TITLE" --body "$PR_BODY"
        shell: /usr/bin/bash -e {0}
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_TITLE: ${{ env.PR_TITLE }}
